# Generated by Django 4.2.6 on 2023-10-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tareas_email_tareas_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='nombre',
        ),
    ]
